trying to batch
jingedawang/StockPredictor pull request #26
Opened 2022-09-22 15:27 UTC by chenshoval

2022-09-23 14:01 UTC, jingedawang commented
The slicing problem is fixed.
The total time for 300 batch is 40 minutes, including 25 minutes of predicting and 15 minutes of database writing.
This is big improvement! We could complete the full prediction in about 8 hours.
If we can optimize the database writing time, the total time will be even shorter.
Thanks for your work! @chenshoval 

Meanwhile, I found you modified some of the interface which will have impacts of the functionality. Please resume them. I will leave some comments there.

2022-09-29 06:14 UTC, chenshoval commented on stock_predictor/service.py
> -def predict_all(date=None, force_update=False):
this change is because in a batch i cannot understand if a single row does not have a prediciton then i overwrite the entire batch because of it.

2022-09-29 06:16 UTC, chenshoval commented on stock_predictor/service.py
> -def predict_all(date=None, force_update=False):
@jingedawang please at your leisure, just comment where you want me to revert the code and ill try! i can work on it IST night so no worries just tell me will complete ASAP

2022-10-02 10:47 UTC, jingedawang requested changes

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> -def predict_all(date=None, force_update=False):
Why remove the `force_update` argument here?

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> -            prediction = predict.predict(row['qlib_id'], start_date='2022-01-01', end_date=datetime.date.today().strftime('%Y-%m-%d'))
If `date is None`, we need to predict for all the stocks on a big date range (from 2022-01-01 to today). This is used when user run `setup.py` at initial time. We shouldn't remove this feature.

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> -def predict_all(date=None, force_update=False):
OK, I got your point. Let's just abandon this feature.

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> -            prediction = predict.predict(row['qlib_id'], start_date='2022-01-01', end_date=datetime.date.today().strftime('%Y-%m-%d'))
Please consider support this feature.

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> +        date = datetime.date.today().strftime('%Y-%m-%d')
Please use different start date and end date as line 66 in last version. We should predict for a longer date range for the initial prediction.

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
Please update the document in line 60, since we removed the `force_update` argument.

2022-10-02 10:47 UTC, jingedawang commented on stock_predictor/service.py
> +def batch(iterable, n=1):
Please add document comment for this method.

2022-10-02 10:49 UTC, chenshoval commented on stock_predictor/service.py
> -            prediction = predict.predict(row['qlib_id'], start_date='2022-01-01', end_date=datetime.date.today().strftime('%Y-%m-%d'))
fixed

2022-10-02 10:50 UTC, chenshoval commented on stock_predictor/service.py
> +        date = datetime.date.today().strftime('%Y-%m-%d')
fixed

2022-10-02 10:51 UTC, chenshoval commented on stock_predictor/service.py
fixed

2022-10-02 11:11 UTC, jingedawang commented on stock_predictor/service.py
> +    Batces an iterable collection returns a collection of collections with n as the size of the inner collections.
Typo: `Batces` should be `Batches`.

2022-10-02 11:13 UTC, jingedawang commented on stock_predictor/service.py
> +        date = '2022-01-01'
We should make start_date and end_date different if date is None.
Let `start_date = '2022-01-01'` and `end_date = datetime.date.today().strftime('%Y-%m-%d')`.

2022-10-02 11:14 UTC, jingedawang commented on stock_predictor/service.py
>      print('before start', datetime.datetime.now())
Please remove this line of debug code. Sorry for adding that in my last commit.

2022-10-02 11:14 UTC, jingedawang commented on stock_predictor/service.py
>      print('before start', datetime.datetime.now())
Also line 84.

2022-10-02 11:16 UTC, jingedawang commented on stock_predictor/service.py
> +        n = batch size
I think this line should use the same format of last line.
```
n: The batch size. Default 1.
```

2022-10-02 11:25 UTC, jingedawang approved these changes

2022-10-02 11:44 UTC, merged